version: "3.1"
services:
  app:
    image: customer-loyalty-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
