name: Build pipeline for customer-loyalty-service

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'liberica'

      - name: Check Kotlin Format
        run: mvn spotless:check

      - name: Run Static Code Analyzer
        run: mvn detekt:check

      - name: Run Test Cases
        run: mvn test

      - name: Build with Maven
        run: mvn clean install

      - name: Run codecov command to populate code coverage
        run: bash <(curl -s https://codecov.io/bash)